linters:
  enable-all: true
  disable:
    # Work on fixing this
    #- reassign
    - reassign
    - interfacebloat
    - maintidx
    - nakedret
    - gocyclo
    - gocognit
    - funlen
    - goconst
    - nestif
    - dupl
    - containedctx
    - cyclop
    - errorlint
    - forcetypeassert
    - nilerr
    - nosprintfhostport
    - exhaustive
    - thelper
    - nonamedreturns
    - nilnil
    - godox
    - goerr113
    - lll
    - nlreturn
    - nosnakecase
    - revive
    - stylecheck
    - wsl
    #- interfacebloat

    # Not working with generics
    # enable in the future
    - contextcheck
    - rowserrcheck
    - sqlclosecheck
    - structcheck
    - wastedassign

    # These are two strict or deprecated
    - deadcode
    - varcheck
    - testpackage
    - paralleltest
    - interfacer
    - ifshort
    - ireturn
    - wrapcheck
    - varnamelen
    - gomnd
    - tagliatelle
    - gochecknoglobals
    - exhaustivestruct
    - exhaustruct
    - golint
    - maligned
    - gochecknoinits
    - scopelint
linters-settings:
  goheader:
    template: |-
      Copyright {{ YEAR-RANGE }} Tigris Data, Inc.

      Licensed under the Apache License, Version 2.0 (the "License");
      you may not use this file except in compliance with the License.
      You may obtain a copy of the License at

           http://www.apache.org/licenses/LICENSE-2.0

      Unless required by applicable law or agreed to in writing, software
      distributed under the License is distributed on an "AS IS" BASIS,
      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
      See the License for the specific language governing permissions and
      limitations under the License.
  lll:
    line-length: 120
