branches:
  - name: rc
    prerelease: true
  - name: alpha
    prerelease: true
  - name: beta
    prerelease: true
  - release
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
