FROM golang:1.18beta1-bullseye

RUN apt-get install make curl git gcc g++

ENV GOPATH=/go
RUN mkdir -p /go/src/tigris

#this is to install dependencies once, during docker build
COPY ./Makefile /go/src/tigris/
COPY ./go.mod /go/src/tigris/

WORKDIR /go/src/tigris

RUN make test_deps

RUN GO111MODULE=on go mod download

RUN rm -rf ./*

CMD make local_test
