# Copyright 2022-2023 Tigris Data, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

server:
  port: 8081

environment: test

search:
  auth_key: ts_test_key
  host: tigris_search

log:
  format: console

secondary_index:
  write_enabled: true
  read_enabled: true
  mutate_enabled: true

auth:
  enabled: true
  enable_namespace_isolation: true
  enable_oauth: true
  log_only: false
  admin_namespaces: tigris_test
  issuers:
    - issuer: http://tigris_gotrue:8086
      algorithm: RS256
    - issuer: http://tigris_gotrue:8086
      algorithm: HS256
      shared_secret_env_key: HS256_SIGNATURE_KEY
  token_cache_size: 100
  audience: https://tigris-test
  oauth_provider: gotrue
  gotrue:
    username_suffix: "@m2m.tigrisdata.com"
    url: http://tigris_gotrue:8086
    admin_username: test
    admin_password: test