apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - network-policy.yaml
configMapGenerator:
  - name: tigrisdb-server-config
    files:
      - server.yaml
