apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: tigrisdb-server-network-policy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: tigrisdb-server
  ingress:
    - {}
  egress:
    - {}
  policyTypes:
    - Ingress
    - Egress
