apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: tigrisdb-server
    app.kubernetes.io/part-of: tigrisdb
    app.kubernetes.io/component: server
  name: tigrisdb-server
spec:
  type: NodePort
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: tigrisdb-server
