apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patchesStrategicMerge:
  - deployment.yaml
images:
  - name: tigrisdb
    newName: prod/tigrisdb
    newTag: v1
