name: cli-test
on:
  push:
    branches:
      - "!release"
      - "!alpha"
      - "!beta"
      - "!rc"
  workflow_call:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install CLI
        run: |
          curl -sSL https://tigris.dev/cli-linux | sudo tar -xz -C .

      - name: Start Tigris server
        run: |
          make run
          sleep 20

      - name: Run CLI tests
        run: noup=1 /bin/bash test/v1/cli/main.sh
