name: publish docker image

on:
  pull_request:
    paths:
      - docker/Dockerfile*
      - scripts/install_*.sh
      - .github/workflows/push-docker-*.yaml
    types:
      - labeled
  merge_group:
    paths:
      - docker/Dockerfile*
      - scripts/install_*.sh
      - .github/workflows/push-docker-*.yaml
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  debug-image:
    if: ${{ github.event.label.name == 'debug image' }}
    uses: ./.github/workflows/push-docker-image.yaml
    secrets: inherit
    with:
      docker_repository: tigrisdata/tigris-debug
      quay_repository: quay.io/tigrisdata/tigris-debug
      file: docker/Dockerfile
      platforms: amd64,arm64
      event_name: ${{ github.event_name }}
      build_args: WITH_DEBUG=1
