name: docker image

on:
  pull_request:
    types:
      - labeled

jobs:
  debug:
    if: ${{ github.event.label.name == 'debug image' }}
    uses: ./.github/workflows/push-docker-image.yaml
    secrets: inherit
    with:
      docker_repository: "tigrisdata/tigris-debug"
      quay_repository: "quay.io/tigrisdata/tigris-debug"
      file: docker/Dockerfile
      platforms: amd64
      event_name: push
