name: docker image

on:
  pull_request:
    paths:
      - docker/Dockerfile*
      - scripts/install_*.sh
      - .github/workflows/push-docker-local.yaml
      - .github/workflows/push-docker-image.yaml
  merge_group:
    paths:
      - docker/Dockerfile*
      - scripts/install_*.sh
      - .github/workflows/push-docker-*.yaml
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  local:
    uses: ./.github/workflows/push-docker-image.yaml
    secrets: inherit
    with:
      docker_repository: "tigrisdata/tigris-local"
      platforms: amd64,arm64
      file: docker/Dockerfile.local
      event_name: ${{ github.event_name }}
