name: docker image

on:
  pull_request:
    paths:
      - docker/Dockerfile*
      - scripts/install_*.sh
      - .github/workflows/push-docker-arm64.yaml
      - .github/workflows/push-docker-image.yaml
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  arm64:
    uses: ./.github/workflows/push-docker-image.yaml
    secrets: inherit
    with:
      docker_repository: "tigrisdata/tigris"
      quay_repository: "quay.io/tigrisdata/tigris"
      file: docker/Dockerfile
      platforms: arm64
      event_name: ${{ github.event_name }}
