name: test local docker image

on:
  pull_request:
    paths:
      - docker/Dockerfile.local
      - scripts/install_local_deps.sh
      - .github/workflows/test-docker-local-image.yaml
  merge_group:
    paths:
      - docker/Dockerfile.local
      - scripts/install_local_deps.sh
      - .github/workflows/test-docker-local-image.yaml
  push:
    branches:
      - main

jobs:
  test-local-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build local image
        run: make docker-local

      - name: Run local image
        run: docker run -d -p 8081:8081 tigris_local

      - name: Run CLI tests
        run: |
          curl -sSL https://tigris.dev/cli-linux | tar -xz -C .
          TIGRIS_URL=localhost:8081 ./tigris ping --timeout 20s
          TIGRIS_TEST_PORT=8081 TIGRIS_CLI_TEST_FAST=1 noup=1 /bin/bash test/v1/cli/main.sh

